# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tero < Formula
  desc "Improve your observability data quality from the terminal"
  homepage "https://usetero.com"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usetero/cli/releases/download/v1.2.3/tero_1.2.3_darwin_amd64.tar.gz"
      sha256 "3c4326c490ecf17488a662618eb52294a8700a516d6d266bf90542c8fb39dcaa"

      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usetero/cli/releases/download/v1.2.3/tero_1.2.3_darwin_arm64.tar.gz"
      sha256 "2eaea4332a44c95ec89a8712ef8e3aad9db2880c72019fe9f1da1574af7dd851"

      def install
        bin.install "tero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.2.3/tero_1.2.3_linux_amd64.tar.gz"
      sha256 "1cf72ef3b1fa0d6235ff5496c9fc70e327bffea18bc0e0a7f21a7e015858dc9a"
      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.2.3/tero_1.2.3_linux_arm64.tar.gz"
      sha256 "8c02f3f7ff93f8df08c62688fa6695671a034cd44ef6d281fcd93eeeb94d8c29"
      def install
        bin.install "tero"
      end
    end
  end

  test do
    system "#{bin}/tero", "--version"
  end
end
