# This file was generated by GoReleaser. DO NOT EDIT.
cask "tero" do
  name "tero"
  desc "Improve your observability data quality from the terminal"
  homepage "https://usetero.com"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tero"

  on_macos do
    on_intel do
      url "https://github.com/usetero/cli/releases/download/v#{version}/tero_#{version}_darwin_amd64.tar.gz"
      sha256 "dc31a2ec1fccb4cad186a4b103302188802c17ec27f402edba73382c959be90a"
    end
    on_arm do
      url "https://github.com/usetero/cli/releases/download/v#{version}/tero_#{version}_darwin_arm64.tar.gz"
      sha256 "10d0c593369ab517221fa591828900ebbab5ab76239c57a42794d35d120a1fbc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/usetero/cli/releases/download/v#{version}/tero_#{version}_linux_amd64.tar.gz"
      sha256 "5638dcd2f51a75158c9ddf214128aa83f430099c2c8cd2ab6fed6c19e00128fc"
    end
    on_arm do
      url "https://github.com/usetero/cli/releases/download/v#{version}/tero_#{version}_linux_arm64.tar.gz"
      sha256 "357f6545a13a2c6c81ac9d22d963dce0f44ba1aa9a8aee937bc343bc04853a77"
    end
  end

  # No zap stanza required
end
