# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Improve your observability data quality from the terminal"
  homepage "https://usetero.com"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usetero/cli/releases/download/v1.0.0/tero_1.0.0_darwin_amd64.tar.gz"
      sha256 "d0c1d80c56d5768835c824c9ad5cd3a848c13c343533ce8bac487ff37d4f1073"

      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usetero/cli/releases/download/v1.0.0/tero_1.0.0_darwin_arm64.tar.gz"
      sha256 "72183c49c33eb4c8dbdac042526d1eca376b2c7f89ce190e822dcff7c932344e"

      def install
        bin.install "tero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.0.0/tero_1.0.0_linux_amd64.tar.gz"
      sha256 "010d3c5956bf23f36970713d59e52227e33bf1056282a5f31818decf1863b09a"
      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.0.0/tero_1.0.0_linux_arm64.tar.gz"
      sha256 "b3893113391ff65248fd4a8e27add38648e4a4450ef9301f80b33f72f40ff7e5"
      def install
        bin.install "tero"
      end
    end
  end

  test do
    system "#{bin}/tero", "--version"
  end
end
