# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tero < Formula
  desc "Improve your observability data quality from the terminal"
  homepage "https://usetero.com"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usetero/cli/releases/download/v1.2.0/tero_1.2.0_darwin_amd64.tar.gz"
      sha256 "c06752fb8f57f2bd7f3aa6726c10006c7928e44be6549df57a1001fa6a630ac1"

      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usetero/cli/releases/download/v1.2.0/tero_1.2.0_darwin_arm64.tar.gz"
      sha256 "a1d2d1988519f54bddc80ddc69826805875759f240c7ab34f5d159d1560b3b34"

      def install
        bin.install "tero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.2.0/tero_1.2.0_linux_amd64.tar.gz"
      sha256 "a29bc5bd4b610ae859d2e67bb1b54387cac451c33ee4638823de56a5aca344dd"
      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.2.0/tero_1.2.0_linux_arm64.tar.gz"
      sha256 "fd30bb539a6eb9bc8825be094cf03a2aec9bc093d2cf027d1cacd101b01794ed"
      def install
        bin.install "tero"
      end
    end
  end

  test do
    system "#{bin}/tero", "--version"
  end
end
