# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tero < Formula
  desc "Improve your observability data quality from the terminal"
  homepage "https://usetero.com"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usetero/cli/releases/download/v1.1.0/tero_1.1.0_darwin_amd64.tar.gz"
      sha256 "cbe6daf9b2ad6fe6c65a8b5442e078e0c74677853c75728be09e828a5139ae15"

      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usetero/cli/releases/download/v1.1.0/tero_1.1.0_darwin_arm64.tar.gz"
      sha256 "a6a627651cb6f9c2b85486802b2af2139cf854e88f2e00473aba9ca2ace76b4b"

      def install
        bin.install "tero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.1.0/tero_1.1.0_linux_amd64.tar.gz"
      sha256 "751d0cf56b4815215baf5e8288abb5acf40f2034da465e9149a7f0f06faff587"
      def install
        bin.install "tero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetero/cli/releases/download/v1.1.0/tero_1.1.0_linux_arm64.tar.gz"
      sha256 "a495ac233bdbf0ab8da3dc273e6a98ccb78d8e236f7824f4b0edfeae9a8d1df3"
      def install
        bin.install "tero"
      end
    end
  end

  test do
    system "#{bin}/tero", "--version"
  end
end
